import { pgTable, varchar, text, timestamp, boolean, serial, numeric, integer } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const users = pgTable("users", {
  id: varchar("id", { length: 255 }).primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name", { length: 255 }),
  email: varchar("email", { length: 255 }).unique(),
  emailVerified: boolean("email_verified").default(false),
  username: varchar("username", { length: 255 }).unique(),
  password: varchar("password", { length: 255 }),
  role: varchar("role", { length: 50 }).default("user"),
  company: varchar("company", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  firstName: varchar("first_name", { length: 255 }),
  lastName: varchar("last_name", { length: 255 }),
  plan: varchar("plan", { length: 50 }).default("free"),
  crmContactId: varchar("crm_contact_id", { length: 255 }),
  avatar: varchar("avatar", { length: 255 }),
  bio: text("bio"),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const applications = pgTable("applications", {
  id: serial("id").primaryKey(),
  applicationId: varchar("application_id", { length: 255 }).unique(),
  contactId: varchar("contact_id", { length: 255 }),
  ghlContactId: varchar("ghl_contact_id", { length: 255 }),
  ghlOpportunityId: varchar("ghl_opportunity_id", { length: 255 }),
  email: varchar("email", { length: 255 }),
  loanType: varchar("loan_type", { length: 100 }),
  loanAmount: numeric("loan_amount", { precision: 15, scale: 2 }),
  loanPurpose: varchar("loan_purpose", { length: 255 }),
  purpose: varchar("purpose", { length: 255 }),
  creditScore: integer("credit_score"),
  businessRevenue: numeric("business_revenue", { precision: 15, scale: 2 }),
  propertyValue: numeric("property_value", { precision: 15, scale: 2 }),
  downPayment: numeric("down_payment", { precision: 15, scale: 2 }),
  propertyType: varchar("property_type", { length: 100 }),
  propertyAddress: text("property_address"),
  speedNeeded: boolean("speed_needed").default(false),
  currentStatus: varchar("current_status", { length: 100 }).default("new"),
  assignedTo: varchar("assigned_to", { length: 255 }),
  notes: text("notes"),
  documents: text("documents"),
  qualificationScore: integer("qualification_score"),
  matchedPartners: text("matched_partners"),
  estimatedClosingDate: timestamp("estimated_closing_date"),
  statusLastUpdated: timestamp("status_last_updated"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const fundingPartners = pgTable("funding_partners", {
  id: varchar("id", { length: 255 }).primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name", { length: 255 }).notNull(),
  type: varchar("type", { length: 100 }),
  specialties: text("specialties"),
  primaryContact: varchar("primary_contact", { length: 255 }),
  contactEmail: varchar("contact_email", { length: 255 }),
  contactPhone: varchar("contact_phone", { length: 50 }),
  website: varchar("website", { length: 255 }),
  minLoanAmount: numeric("min_loan_amount", { precision: 15, scale: 2 }),
  maxLoanAmount: numeric("max_loan_amount", { precision: 15, scale: 2 }),
  interestRateRange: varchar("interest_rate_range", { length: 100 }),
  typicalLTV: varchar("typical_ltv", { length: 50 }),
  avgClosingTime: integer("avg_closing_time"),
  requiredCreditScore: integer("required_credit_score"),
  geographicFocus: text("geographic_focus"),
  productTypes: text("product_types"),
  isActive: boolean("is_active").default(true),
  rating: numeric("rating", { precision: 3, scale: 2 }),
  reviewCount: integer("review_count").default(0),
  lastActivityDate: timestamp("last_activity_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
